spring:
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: Armin#123
    driver-class-name: org.postgresql.Driver
server:
  port: 8080
